apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Matching the PVC request
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Adjust if needed (e.g., ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc  # Use a common StorageClass for EFS
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05b0878594b65b722  # Replace with your EFS File System ID
