apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap  # Add this parameter for EFS
  fileSystemId: <your-efs-file-system-id>  # Replace with your actual EFS file system ID
  directoryPerms: "700"
volumeBindingMode: Immediate

